# Generated by Django 5.2.9 on 2025-12-11 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Winery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("address", models.TextField(blank=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "winery",
                "verbose_name_plural": "wineries",
                "db_table": "wineries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WineryMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CONSULTANT", "Consultant"),
                            ("WINERY_OWNER", "Winery Owner"),
                            ("WINEMAKER", "Winemaker"),
                            ("CELLAR_STAFF", "Cellar Staff"),
                            ("LAB", "Lab Personnel"),
                        ],
                        default="CELLAR_STAFF",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="winery_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "winery membership",
                "verbose_name_plural": "winery memberships",
                "db_table": "winery_memberships",
                "ordering": ["winery__name", "user__email"],
                "unique_together": {("user", "winery")},
            },
        ),
    ]
