# Generated by Django 5.2.9 on 2025-12-31 14:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0002_convert_to_fk"),
        ("harvest", "0002_alter_batch_must_volume_l"),
        ("production", "0001_initial"),
        ("wineries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Material name (e.g., Potassium Metabisulfite)",
                        max_length=200,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, help_text="Optional SKU/product code", max_length=50
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ADDITIVE", "Additive"),
                            ("STABILIZER", "Stabilizer"),
                            ("FINING_AGENT", "Fining Agent"),
                            ("YEAST", "Yeast"),
                            ("NUTRIENT", "Nutrient"),
                            ("ENZYME", "Enzyme"),
                            ("ACID", "Acid"),
                            ("TANNIN", "Tannin"),
                            ("OAK", "Oak Product"),
                            ("CLEANING", "Cleaning Agent"),
                            ("PACKAGING", "Packaging Material"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Material category",
                        max_length=20,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("ml", "Milliliter"),
                            ("l", "Liter"),
                            ("unit", "Unit"),
                            ("pack", "Pack"),
                        ],
                        help_text="Unit of measurement",
                        max_length=10,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, help_text="Supplier name", max_length=200
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes, specifications"
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Alert when stock falls below this level",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this material still in use?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "winery",
                    models.ForeignKey(
                        help_text="Winery that owns this material",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_material",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Addition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantity added",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "addition_date",
                    models.DateTimeField(help_text="When the addition was made"),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        help_text="Purpose of addition (e.g., SO₂ adjustment, clarification)",
                        max_length=200,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                (
                    "target_volume_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Volume of wine at time of addition (L)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dosage_rate",
                    models.CharField(
                        blank=True,
                        help_text="Calculated dosage rate (e.g., 50 mg/L SO₂)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="additions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "barrel",
                    models.ForeignKey(
                        blank=True,
                        help_text="Barrel (if added to barrel)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additions",
                        to="equipment.barrel",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Batch (if added to batch)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additions",
                        to="harvest.batch",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tank (if added to tank)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additions",
                        to="equipment.tank",
                    ),
                ),
                (
                    "wine_lot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Wine lot (if added to lot)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additions",
                        to="production.winelot",
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additions",
                        to="wineries.winery",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        help_text="Material added",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="additions",
                        to="inventory.material",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_addition",
                "ordering": ["-addition_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE", "Purchase/Delivery"),
                            ("ADJUSTMENT", "Inventory Adjustment"),
                            ("TRANSFER", "Transfer Between Locations"),
                            ("USAGE", "Usage (Addition to Wine)"),
                            ("WASTE", "Waste/Disposal"),
                            ("RETURN", "Return to Supplier"),
                        ],
                        help_text="Type of movement",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Quantity moved (positive for additions, negative for removals)",
                        max_digits=12,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("MAIN_STORAGE", "Main Storage"),
                            ("CELLAR", "Cellar"),
                            ("LAB", "Laboratory"),
                            ("BOTTLING_LINE", "Bottling Line"),
                            ("WAREHOUSE", "Warehouse"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Location affected",
                        max_length=20,
                    ),
                ),
                (
                    "destination_location",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MAIN_STORAGE", "Main Storage"),
                            ("CELLAR", "Cellar"),
                            ("LAB", "Laboratory"),
                            ("BOTTLING_LINE", "Bottling Line"),
                            ("WAREHOUSE", "Warehouse"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Destination location (for transfers)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "movement_date",
                    models.DateTimeField(help_text="When the movement occurred"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="PO number, invoice number, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per unit (for purchases)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Additional notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="material_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        help_text="Material moved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.material",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_material_movement",
                "ordering": ["-movement_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MaterialStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("MAIN_STORAGE", "Main Storage"),
                            ("CELLAR", "Cellar"),
                            ("LAB", "Laboratory"),
                            ("BOTTLING_LINE", "Bottling Line"),
                            ("WAREHOUSE", "Warehouse"),
                            ("OTHER", "Other"),
                        ],
                        default="MAIN_STORAGE",
                        help_text="Storage location",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        help_text="Current quantity in stock",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.ForeignKey(
                        help_text="Material",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_locations",
                        to="inventory.material",
                    ),
                ),
            ],
            options={
                "db_table": "inventory_material_stock",
            },
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["winery", "category"], name="inventory_m_winery__ef7282_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="material",
            index=models.Index(
                fields=["winery", "is_active"], name="inventory_m_winery__2b487a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="material",
            unique_together={("winery", "code")},
        ),
        migrations.AddIndex(
            model_name="addition",
            index=models.Index(
                fields=["winery", "-addition_date"],
                name="inventory_a_winery__c63db6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="addition",
            index=models.Index(
                fields=["material"], name="inventory_a_materia_8787a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="addition",
            index=models.Index(fields=["tank"], name="inventory_a_tank_id_b2e50f_idx"),
        ),
        migrations.AddIndex(
            model_name="addition",
            index=models.Index(
                fields=["barrel"], name="inventory_a_barrel__094df1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialmovement",
            index=models.Index(
                fields=["material", "-movement_date"],
                name="inventory_m_materia_e8f19b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialmovement",
            index=models.Index(
                fields=["movement_type"], name="inventory_m_movemen_19afef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="materialstock",
            index=models.Index(
                fields=["material", "location"], name="inventory_m_materia_d8637f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="materialstock",
            unique_together={("material", "location")},
        ),
    ]
