# Generated by Django 5.2.9 on 2025-12-17 18:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("harvest", "0001_initial"),
        ("wineries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WineLot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lot_code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "vintage",
                    models.PositiveIntegerField(help_text="Vintage year (e.g., 2024)"),
                ),
                (
                    "wine_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Cabernet Sauvignon, Rosé Blend",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("AGING", "Aging"),
                            ("READY", "Ready for Bottling"),
                            ("BOTTLED", "Bottled"),
                            ("SOLD", "Sold Out"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                (
                    "initial_volume_l",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Initial volume when lot was created",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_volume_l",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current remaining volume",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_barrel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wine_lots",
                        to="equipment.barrel",
                    ),
                ),
                (
                    "current_tank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wine_lots",
                        to="equipment.tank",
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wine_lots",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "ordering": ["-vintage", "lot_code"],
            },
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("FILL", "Fill Tank"),
                            ("RACK", "Racking"),
                            ("BLEND", "Blending"),
                            ("TOP_UP", "Topping Up"),
                            ("DRAIN", "Drain"),
                            ("BARREL_FILL", "Barrel Fill"),
                            ("BARREL_EMPTY", "Barrel Empty"),
                            ("BARREL_RACK", "Barrel Racking"),
                            ("FILTER", "Filtration"),
                            ("BOTTLE", "Bottling"),
                        ],
                        default="RACK",
                        max_length=20,
                    ),
                ),
                (
                    "transfer_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "volume_l",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Volume transferred in liters",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Temperature at transfer in Celsius",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        help_text="Explicit batch attribution for this transfer",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers",
                        to="harvest.batch",
                    ),
                ),
                (
                    "destination_barrel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="equipment.barrel",
                    ),
                ),
                (
                    "destination_tank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="equipment.tank",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_barrel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="equipment.barrel",
                    ),
                ),
                (
                    "source_tank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="equipment.tank",
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="wineries.winery",
                    ),
                ),
                (
                    "wine_lot",
                    models.ForeignKey(
                        blank=True,
                        help_text="Wine lot this transfer belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers",
                        to="production.winelot",
                    ),
                ),
            ],
            options={
                "ordering": ["-transfer_date"],
            },
        ),
        migrations.CreateModel(
            name="LotBatchLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "volume_l",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Volume from this batch in the lot",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of lot from this batch",
                        max_digits=5,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lot_links",
                        to="harvest.batch",
                    ),
                ),
                (
                    "wine_lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_links",
                        to="production.winelot",
                    ),
                ),
            ],
            options={
                "ordering": ["-percentage"],
            },
        ),
        migrations.AddIndex(
            model_name="winelot",
            index=models.Index(
                fields=["winery", "status"], name="production__winery__d1af4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="winelot",
            index=models.Index(
                fields=["vintage"], name="production__vintage_3d0bdb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="winelot",
            unique_together={("winery", "lot_code")},
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["winery", "-transfer_date"],
                name="production__winery__fb3097_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["source_tank"], name="production__source__2ca402_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["destination_tank"], name="production__destina_5bbc38_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lotbatchlink",
            unique_together={("wine_lot", "batch")},
        ),
    ]
