# Generated by Django 5.2.9 on 2025-12-17 20:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("harvest", "0001_initial"),
        ("production", "0001_initial"),
        ("wineries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("TANK", "Tank"),
                            ("BARREL", "Barrel"),
                            ("WINE_LOT", "Wine Lot"),
                            ("BATCH", "Batch"),
                            ("BLEND", "Blend Sample"),
                            ("BOTTLE", "Bottle"),
                            ("OTHER", "Other"),
                        ],
                        default="TANK",
                        max_length=20,
                    ),
                ),
                (
                    "analysis_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "sample_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When sample was taken (if different)",
                        null=True,
                    ),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Sample temperature in Celsius",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(-10),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="pH value (2.0 - 5.0)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("2.0")),
                            django.core.validators.MaxValueValidator(Decimal("5.0")),
                        ],
                    ),
                ),
                (
                    "ta_gl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Titratable acidity in g/L (as tartaric)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("20")),
                        ],
                    ),
                ),
                (
                    "va_gl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Volatile acidity in g/L (as acetic)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("3")),
                        ],
                    ),
                ),
                (
                    "brix",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Brix degrees (sugar content)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-5")),
                            django.core.validators.MaxValueValidator(Decimal("40")),
                        ],
                    ),
                ),
                (
                    "density",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Density/specific gravity at 20°C",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.9")),
                            django.core.validators.MaxValueValidator(Decimal("1.2")),
                        ],
                    ),
                ),
                (
                    "residual_sugar_gl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Residual sugar in g/L",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("400")),
                        ],
                    ),
                ),
                (
                    "free_so2_mgl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Free SO₂ in mg/L",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("200")),
                        ],
                    ),
                ),
                (
                    "total_so2_mgl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Total SO₂ in mg/L",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("400")),
                        ],
                    ),
                ),
                (
                    "alcohol_abv",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Alcohol % by volume",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("25")),
                        ],
                    ),
                ),
                (
                    "malic_acid_gl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Malic acid in g/L",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                    ),
                ),
                (
                    "lactic_acid_gl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Lactic acid in g/L",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("5")),
                        ],
                    ),
                ),
                (
                    "tartaric_acid_gl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Tartaric acid in g/L",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                    ),
                ),
                (
                    "citric_acid_gl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Citric acid in g/L",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("3")),
                        ],
                    ),
                ),
                (
                    "color_intensity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Color intensity (sum of absorbances)",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("30")),
                        ],
                    ),
                ),
                (
                    "color_hue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Color hue (A420/A520)",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("5")),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analyzed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "barrel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="equipment.barrel",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="harvest.batch",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="equipment.tank",
                    ),
                ),
                (
                    "wine_lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to="production.winelot",
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis",
                "verbose_name_plural": "Analyses",
                "ordering": ["-analysis_date"],
                "indexes": [
                    models.Index(
                        fields=["winery", "-analysis_date"],
                        name="lab_analysi_winery__d7252a_idx",
                    ),
                    models.Index(
                        fields=["tank", "-analysis_date"],
                        name="lab_analysi_tank_id_df6ece_idx",
                    ),
                    models.Index(
                        fields=["barrel", "-analysis_date"],
                        name="lab_analysi_barrel__080cb4_idx",
                    ),
                    models.Index(
                        fields=["wine_lot", "-analysis_date"],
                        name="lab_analysi_wine_lo_1f6934_idx",
                    ),
                    models.Index(
                        fields=["batch", "-analysis_date"],
                        name="lab_analysi_batch_i_61c09e_idx",
                    ),
                ],
            },
        ),
    ]
