# Generated by Django 5.2.9 on 2025-12-22 00:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("lab", "0001_initial"),
        ("production", "0001_initial"),
        ("wineries", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Auto-generated or manual work order code",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief description of the work order", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed instructions or notes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("VERIFIED", "Verified"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the work should be performed",
                        null=True,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Deadline for completion", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the work order was completed",
                        null=True,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Primary person responsible",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_orders_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_orders",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_for", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "line_no",
                    models.PositiveIntegerField(
                        default=1, help_text="Order within the work order"
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Transfer"),
                            ("ADDITION", "Addition"),
                            ("ANALYSIS", "Analysis"),
                            ("INSPECTION", "Inspection"),
                            ("CLEANING", "Cleaning"),
                            ("MAINTENANCE", "Maintenance"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "target_volume_l",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target volume for transfer",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "dosage_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Dosage amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "dosage_unit",
                    models.CharField(
                        blank=True, help_text="e.g., g/L, mL/hL", max_length=20
                    ),
                ),
                (
                    "material_name",
                    models.CharField(
                        blank=True,
                        help_text="Material name (until inventory app is ready)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="What needs to be done", max_length=500
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or results"
                    ),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "executed_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_line",
                        to="lab.analysis",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_lines_executed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "executed_transfer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_line",
                        to="production.transfer",
                    ),
                ),
                (
                    "from_tank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_lines_from",
                        to="equipment.tank",
                    ),
                ),
                (
                    "target_barrel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_lines",
                        to="equipment.barrel",
                    ),
                ),
                (
                    "target_tank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_lines",
                        to="equipment.tank",
                    ),
                ),
                (
                    "to_tank",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_order_lines_to",
                        to="equipment.tank",
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_order_lines",
                        to="wineries.winery",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="work_orders.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["work_order", "line_no"],
            },
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["winery", "status"], name="work_orders_winery__de48b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["winery", "assigned_to", "status"],
                name="work_orders_winery__550cfd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(
                fields=["scheduled_for"], name="work_orders_schedul_5d8c50_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workorder",
            unique_together={("winery", "code")},
        ),
        migrations.AddIndex(
            model_name="workorderline",
            index=models.Index(
                fields=["work_order", "status"], name="work_orders_work_or_bd6389_idx"
            ),
        ),
    ]
