# Generated by Django 5.2.9 on 2025-12-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Brief description (auto-generated from tasks if blank)",
                max_length=200,
            ),
        ),
    ]
