# Generated by Django 5.2.9 on 2025-12-11 21:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wineries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrapeVariety",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                (
                    "color",
                    models.CharField(
                        choices=[("RED", "Red"), ("WHITE", "White"), ("ROSE", "Rosé")],
                        default="RED",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grape_varieties",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grape Variety",
                "verbose_name_plural": "Grape Varieties",
                "ordering": ["name"],
                "unique_together": {("winery", "code"), ("winery", "name")},
            },
        ),
        migrations.CreateModel(
            name="Grower",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="growers",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grower",
                "verbose_name_plural": "Growers",
                "ordering": ["name"],
                "unique_together": {("winery", "name")},
            },
        ),
        migrations.CreateModel(
            name="VineyardBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("subregion", models.CharField(blank=True, max_length=100)),
                (
                    "area_ha",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Area in hectares",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "elevation_m",
                    models.IntegerField(
                        blank=True,
                        help_text="Elevation in meters",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("soil_type", models.CharField(blank=True, max_length=100)),
                ("year_planted", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vineyard_blocks",
                        to="master_data.grower",
                    ),
                ),
                (
                    "primary_variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_blocks",
                        to="master_data.grapevariety",
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vineyard_blocks",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vineyard Block",
                "verbose_name_plural": "Vineyard Blocks",
                "ordering": ["grower__name", "name"],
                "unique_together": {("winery", "code")},
            },
        ),
    ]
