# Generated by Django 5.2.9 on 2025-12-22 23:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TankMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tank Material",
                "verbose_name_plural": "Tank Materials",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WoodType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("origin_country", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wood Type",
                "verbose_name_plural": "Wood Types",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
