# Generated by Django 5.2.9 on 2025-12-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0003_populate_tank_materials_wood_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="vineyardblock",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="GPS latitude coordinate",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vineyardblock",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="GPS longitude coordinate",
                max_digits=10,
                null=True,
            ),
        ),
    ]
