# Generated by Django 5.2.9 on 2025-12-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0004_add_vineyard_coordinates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vineyardblock",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="GPS latitude coordinate",
                max_digits=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vineyardblock",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="GPS longitude coordinate",
                max_digits=11,
                null=True,
            ),
        ),
    ]
