# Generated by Django 5.2.9 on 2025-12-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0005_update_coordinate_precision"),
        ("wineries", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vineyardblock",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="vineyardblock",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name="vineyardblock",
            constraint=models.UniqueConstraint(
                condition=models.Q(("code__isnull", False)),
                fields=("winery", "code"),
                name="unique_winery_code_when_not_null",
            ),
        ),
    ]
