# Generated by Django 5.2.9 on 2025-12-30 15:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master_data", "0006_fix_vineyard_code_unique_constraint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vineyardblock",
            name="area_ha",
        ),
        migrations.RemoveField(
            model_name="vineyardblock",
            name="primary_variety",
        ),
        migrations.AddField(
            model_name="vineyardblock",
            name="area_acres",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Area in acres",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="VineyardVariety",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage of vineyard area (optional)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Mark as the primary variety for this vineyard",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variety",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vineyard_plantings",
                        to="master_data.grapevariety",
                    ),
                ),
                (
                    "vineyard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variety_plantings",
                        to="master_data.vineyardblock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vineyard Variety",
                "verbose_name_plural": "Vineyard Varieties",
                "ordering": ["-is_primary", "variety__name"],
                "unique_together": {("vineyard", "variety")},
            },
        ),
        migrations.AddField(
            model_name="vineyardblock",
            name="varieties",
            field=models.ManyToManyField(
                blank=True,
                help_text="Grape varieties grown in this vineyard",
                related_name="vineyard_blocks",
                through="master_data.VineyardVariety",
                to="master_data.grapevariety",
            ),
        ),
    ]
