# Generated by Django 5.2.9 on 2025-12-11 21:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wineries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Barrel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique barrel identifier", max_length=20
                    ),
                ),
                (
                    "volume_l",
                    models.DecimalField(
                        decimal_places=2,
                        default=225,
                        help_text="Capacity in liters (standard: 225L)",
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_volume_l",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "wood_type",
                    models.CharField(
                        choices=[
                            ("FRENCH_OAK", "French Oak"),
                            ("AMERICAN_OAK", "American Oak"),
                            ("HUNGARIAN_OAK", "Hungarian Oak"),
                            ("ACACIA", "Acacia"),
                            ("CHESTNUT", "Chestnut"),
                            ("OTHER", "Other"),
                        ],
                        default="FRENCH_OAK",
                        max_length=20,
                    ),
                ),
                (
                    "toast_level",
                    models.CharField(
                        choices=[
                            ("LIGHT", "Light"),
                            ("MEDIUM", "Medium"),
                            ("MEDIUM_PLUS", "Medium Plus"),
                            ("HEAVY", "Heavy"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "cooper",
                    models.CharField(
                        blank=True, help_text="Barrel manufacturer", max_length=100
                    ),
                ),
                (
                    "vintage_year",
                    models.IntegerField(
                        blank=True, help_text="Year the barrel was made", null=True
                    ),
                ),
                (
                    "first_use_year",
                    models.IntegerField(
                        blank=True, help_text="First year used for wine", null=True
                    ),
                ),
                (
                    "use_count",
                    models.IntegerField(default=0, help_text="Number of times used"),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMPTY", "Empty"),
                            ("IN_USE", "In Use"),
                            ("CONDITIONING", "Conditioning"),
                            ("RETIRED", "Retired"),
                        ],
                        default="EMPTY",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barrels",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Barrel",
                "verbose_name_plural": "Barrels",
                "ordering": ["code"],
                "unique_together": {("winery", "code")},
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=20)),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("PUMP", "Pump"),
                            ("PRESS", "Press"),
                            ("FILTER", "Filter"),
                            ("CRUSHER", "Crusher/Destemmer"),
                            ("BOTTLING", "Bottling Line"),
                            ("LABELER", "Labeler"),
                            ("FORKLIFT", "Forklift"),
                            ("TEMPERATURE", "Temperature Control"),
                            ("MEASUREMENT", "Measurement"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "capacity",
                    models.CharField(
                        blank=True,
                        help_text="Capacity/throughput description",
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In Use"),
                            ("MAINTENANCE", "Maintenance"),
                            ("OUT_OF_SERVICE", "Out of Service"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
                "ordering": ["name"],
                "unique_together": {("winery", "code")},
            },
        ),
        migrations.CreateModel(
            name="Tank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique tank identifier (e.g., A01, B12)",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                (
                    "tank_type",
                    models.CharField(
                        choices=[
                            ("FERMENTATION", "Fermentation"),
                            ("STORAGE", "Storage"),
                            ("BLENDING", "Blending"),
                            ("SETTLING", "Settling"),
                            ("TEMPERATURE_CONTROL", "Temperature Control"),
                        ],
                        default="STORAGE",
                        max_length=30,
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("STAINLESS", "Stainless Steel"),
                            ("CONCRETE", "Concrete"),
                            ("FIBERGLASS", "Fiberglass"),
                            ("OAK", "Oak"),
                            ("PLASTIC", "Food-Grade Plastic"),
                        ],
                        default="STAINLESS",
                        max_length=20,
                    ),
                ),
                (
                    "capacity_l",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum capacity in liters",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_volume_l",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current volume in liters",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Physical location in winery",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EMPTY", "Empty"),
                            ("IN_USE", "In Use"),
                            ("CLEANING", "Cleaning"),
                            ("MAINTENANCE", "Maintenance"),
                            ("OUT_OF_SERVICE", "Out of Service"),
                        ],
                        default="EMPTY",
                        max_length=20,
                    ),
                ),
                ("has_cooling", models.BooleanField(default=False)),
                ("has_heating", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tanks",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tank",
                "verbose_name_plural": "Tanks",
                "ordering": ["code"],
                "unique_together": {("winery", "code")},
            },
        ),
    ]
