# Generated by Django 5.2.9 on 2025-12-21 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("production", "0001_initial"),
        ("wineries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TankLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_datetime",
                    models.DateTimeField(
                        help_text="Timestamp of the original transfer"
                    ),
                ),
                (
                    "delta_volume_l",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Volume change in liters (positive=in, negative=out)",
                        max_digits=10,
                    ),
                ),
                (
                    "composition_key_type",
                    models.CharField(
                        choices=[
                            ("BATCH", "Batch"),
                            ("WINE_LOT", "Wine Lot"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="BATCH",
                        max_length=20,
                    ),
                ),
                (
                    "composition_key_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the batch or wine lot (null for UNKNOWN)",
                        null=True,
                    ),
                ),
                (
                    "composition_key_label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label for the composition key",
                        max_length=100,
                    ),
                ),
                (
                    "derived_source",
                    models.CharField(
                        choices=[
                            ("EXPLICIT", "Explicit Attribution"),
                            ("INHERITED", "Inherited from Source"),
                            ("UNKNOWN", "Unknown Source"),
                        ],
                        default="EXPLICIT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="equipment.tank",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        help_text="The transfer event that created this entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="production.transfer",
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tank_ledger_entries",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tank Ledger Entry",
                "verbose_name_plural": "Tank Ledger Entries",
                "ordering": ["event_datetime", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["winery", "tank", "event_datetime"],
                        name="ledger_tank_winery__1a88eb_idx",
                    ),
                    models.Index(
                        fields=["tank", "composition_key_type", "composition_key_id"],
                        name="ledger_tank_tank_id_8d473b_idx",
                    ),
                    models.Index(
                        fields=["transfer"], name="ledger_tank_transfe_d4a700_idx"
                    ),
                ],
            },
        ),
    ]
