# Generated by Django 5.2.9 on 2025-12-30 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvest", "0002_alter_batch_must_volume_l"),
        ("ledger", "0001_initial"),
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tankledger",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="The batch intake event that created this entry",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="harvest.batch",
            ),
        ),
        migrations.AlterField(
            model_name="tankledger",
            name="event_datetime",
            field=models.DateTimeField(
                help_text="Timestamp of the original transfer or batch intake"
            ),
        ),
        migrations.AlterField(
            model_name="tankledger",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                help_text="The transfer event that created this entry",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="production.transfer",
            ),
        ),
    ]
