# Generated by Django 5.2.9 on 2025-12-11 21:48

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        ("master_data", "0001_initial"),
        ("wineries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_code",
                    models.CharField(
                        help_text="Auto-generated batch code (e.g., 2024-001)",
                        max_length=50,
                    ),
                ),
                ("intake_date", models.DateField(default=datetime.date.today)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("OWN", "Own Vineyard"),
                            ("PURCHASED", "Purchased Grapes"),
                            ("MIXED", "Mixed Sources"),
                        ],
                        default="OWN",
                        max_length=20,
                    ),
                ),
                (
                    "grape_weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total grape weight in kg",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "must_volume_l",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimated must volume in liters",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("INTAKE", "Intake"),
                            ("CRUSHING", "Crushing"),
                            ("FERMENTATION", "Fermentation"),
                            ("POST_FERMENT", "Post-Fermentation"),
                            ("AGING", "Aging"),
                            ("BLENDING", "Blending"),
                            ("BOTTLING", "Bottling"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="INTAKE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initial_tank",
                    models.ForeignKey(
                        blank=True,
                        help_text="Tank where grapes were initially placed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initial_batches",
                        to="equipment.tank",
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch",
                "verbose_name_plural": "Batches",
                "ordering": ["-intake_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BatchSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight in kg from this source",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "is_estimated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the weight is estimated vs measured",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="harvest.batch",
                    ),
                ),
                (
                    "variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_sources",
                        to="master_data.grapevariety",
                    ),
                ),
                (
                    "vineyard_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_sources",
                        to="master_data.vineyardblock",
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_sources",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Source",
                "verbose_name_plural": "Batch Sources",
                "ordering": ["-weight_kg"],
            },
        ),
        migrations.CreateModel(
            name="HarvestSeason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.IntegerField(help_text="Harvest year (vintage)")),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text='Optional name for the season (e.g., "2024 Harvest")',
                        max_length=100,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this is the current active season",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvest_seasons",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Harvest Season",
                "verbose_name_plural": "Harvest Seasons",
                "ordering": ["-year"],
                "unique_together": {("winery", "year")},
            },
        ),
        migrations.AddField(
            model_name="batch",
            name="harvest_season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="harvest.harvestseason",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="batch",
            unique_together={("winery", "batch_code")},
        ),
    ]
