# Generated by Django 5.2.9 on 2025-12-30 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("harvest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="must_volume_l",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Must volume in liters",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
