# Generated by Django 5.2.9 on 2026-01-19 09:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_convert_to_fk"),
        ("harvest", "0002_alter_batch_must_volume_l"),
        ("wineries", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchFraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fraction_type",
                    models.CharField(
                        choices=[
                            ("FREE_RUN", "Free Run"),
                            ("PRESS_1", "1st Press"),
                            ("PRESS_2", "2nd Press"),
                            ("PRESS_3", "3rd Press"),
                            ("SKIN_CONTACT", "Skin Contact"),
                            ("SETTLING", "Settling"),
                            ("RACKING", "Racking"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of fraction (e.g., Free Run, Press)",
                        max_length=20,
                    ),
                ),
                (
                    "fraction_code",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated code (e.g., 2024-001-FR, 2024-001-P1)",
                        max_length=50,
                    ),
                ),
                (
                    "volume_l",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Volume in liters",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "separation_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this fraction was separated/pressed",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Parent batch this fraction belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fractions",
                        to="harvest.batch",
                    ),
                ),
                (
                    "tank",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current tank storing this fraction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_fractions",
                        to="equipment.tank",
                    ),
                ),
                (
                    "winery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_fractions",
                        to="wineries.winery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Batch Fraction",
                "verbose_name_plural": "Batch Fractions",
                "ordering": ["batch", "separation_datetime", "fraction_type"],
                "unique_together": {("winery", "fraction_code")},
            },
        ),
    ]
