# Generated by Django 5.2.9 on 2026-01-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("harvest", "0003_batchfraction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="initial_tank",
        ),
    ]
